#!/bin/bash
echo "Installing edge browser";
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc;
sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/edge -y;
sudo dnf install microsoft-edge-stable -y;
