#!/bin/bash
gsettings set org.gnome.desktop.wm.preferences num-workspaces 3;
gsettings set org.gnome.desktop.wm.preferences workspace-names "['web', 'dev', 'misc']";
gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close";
# gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar "toggle-minimize";
gsettings set org.gnome.mutter workspaces-only-on-primary false;
gsettings set org.gnome.mutter dynamic-workspaces false;
gsettings set org.gnome.mutter auto-maximize false;
gsettings set org.gnome.shell.app-switcher current-workspace-only true;
gsettings set org.gnome.software download-updates false;

# dash-to-panel
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel panel-positions '{"0":"TOP"}';
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel panel-sizes '{"0":36}';
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel appicon-margin 2;
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel appicon-padding 2;
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel show-appmenu true;
gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ set org.gnome.shell.extensions.dash-to-panel isolate-workspace true;
